### ISSUE TITLE
OpenShift Origin VM deployment sets OPENSHIFT_CLOUD_DOMAIN to example.com

### ISSUE THREAD

**Issue by ghost** [openshift/origin-server#3660]
I followed the steps outlined at http://openshift.github.io/documentation/oo_deployment_guide_vm.html to run a local instance of openshift origin on my Fedora 19 laptop.  When I create jenkins-enabled app and push to it the build fails with the following error.

ssh: Could not resolve hostname appname-domainname.example.com: Name or service not known

It seems to me that it should be preconfigured with the openshift.local domain defined via mDNS, but I'm no expert.

Also, from http://lists.openshift.redhat.com/openshift-archives/users/2013-September/msg00009.html it appears there isn't a convenient way to change the OPENSHIFT_CLOUD_NAME after the fact.

**Comment by tiwillia** [comment]
I can verify that this has been resolved. Starting a VM, I see the hostname has been set appropriately:

![origin-server_issue360](https://cloud.githubusercontent.com/assets/5197933/8574521/1195d210-2565-11e5-8f2e-eec7ba6f3937.png)

Creating an application, we can see that the CLOUD_DOMAIN is properly set to openshift.local:

![origin-server_issue3660_2](https://cloud.githubusercontent.com/assets/5197933/8574926/49fad9c8-2567-11e5-9b25-c9644fe95507.png)

Since this issue was submitted, the OPENSHIFT_CLOUD_NAME was changed to CLOUD_DOMAIN. The domain can easily be changed assuming no applications exist yet in the environment.

@danmcp we can close this out.
