### ISSUE TITLE
phpmyadmin-3 + MySQL 5.1

### ISSUE THREAD

**Issue by clasik** [openshift/origin-server#5550]
Hi.

I am installed Openshift Origin Server with cartridge:
-10gen-mms-agent-0.1 10gen Mongo Monitoring Service Agent
-cron-1.4            Cron 1.4
-jenkins-client-1    Jenkins Client
-mariadb-5.5         MariaDB 5.5
-mongodb-2.2         MongoDB 2.2
-mysql-5.1           MySQL 5.1
-phpmyadmin-3        phpMyAdmin 3.5
-postgresql-9.2      PostgreSQL 9.2
-haproxy-1.4         Web Load Balancer

I need creat a app with MySQL 5.1 + phpMyAdmin 3.5. 
I had add MySQL Cartridge.
But when i am adding phpMyAdmin cartridge, get this error:
Cartridge 'phpmyadmin-3' can not be added without cartridge 'mariadb'.

I had look "MySQL 5.5" and "phpMyAdmin 4" cartridges in Google, Github, Red Hat Documentation, OO Documentation.... but i not found one.

Help Me, thanks.

**Comment by tiwillia** [comment]
This issue is a bit odd, I can't explain it. Since the issue was submitted, better versions of these cartridges have been released. phpMyAdmin 3.5 is no longer used at all.

I can't reproduce this problem using a PHP 5.3 + MySQL 5.1 app and adding a phpMyAdmin 4 cartridge. The cartridge is added and works without issue.

For comparison, the most recent openshift-origin-common version where this appears to be resolved is: `rubygem-openshift-origin-common-1.25.2.2-1.el6.noarch`

@danmcp this can be closed

@clasik if you are still experiencing this issue with phpMyAdmin 4, please re-open this issue.
