### ISSUE TITLE
Openshift Origin + MySQL 5.5

### ISSUE THREAD

**Issue by clasik** [openshift/origin-server#5658]
How install openshift-origin-cartridge-mysql-5.5 ?
I can only install openshift-origin-cartridge-mysql-5.1, but i need install openshift-origin-cartridge-mysql-5.5 for Aerogear 11.

And, How install openshift-origin-cartridge-phpmyadmin-4 ?

Thanks!

**Comment by tiwillia** [comment]
Sorry for the very late reply here. The mysql-5.5 and phpmyadmin-4 cartridges can be installed in the usual way.

First, install the cartridge on the node host(s):
```
yum install -y openshift-origin-cartridge-mysql openshift-origin-cartridge-phpmyadmin
```
Restart the mcollective service:
```
service ruby193-mcollective restart
```
Then, import the cartridge to the broker's cartridge list by running the following on one broker host:
```
oo-admin-broker-cache --clear
oo-admin-console-cache --clear
oo-admin-clt-cartridge --import-profile --activate
```
The cartridges should now be able to be used through `rhc` or the openshift console. You can verify this by listing cartridges with the `rhc cartridges` command.

The cartridge can also be installed manually instead of through yum by using the `oo-admin-cartridge` command and the `origin-server` source:
```
git clone https://github.com/openshift/origin-server
cp -r origin-server/cartridges/openshift-origin-cartridge-mysql /usr/libexec/openshift/cartridges/mysql
oo-admin-cartridge -a install -s /usr/libexec/openshift/cartridges/mysql
```

See the ["Adding Cartridges" section of the Administration Guide](https://docs.openshift.org/origin-m4/oo_administration_guide.html#adding-cartridges) for more information.

I can verify that this should work with the most recent codebase. If you are still experiencing issues, please let us know. Otherwise, @danmcp we can probably close this out.
