### ISSUE TITLE
oo-install fails to setup properly scalable apps

### ISSUE THREAD

**Issue by Fale** [openshift/origin-server#5690]
I've installed oo-install on a clean CentOS 6.5. If I create a PHP app non-scalable, it works properly, but if I try to create a PHP app scalable, it returns:

Unable to complete the requested operation. Show less
System proxy set for 55591=>127.8.208.1:8080 failed(1): stdout: -I rhc-app-comm 1 -d 127.8.208.1 -p tcp --dport 8080 -j ACCEPT -m comment --comment 55591
 stderr: iptables: No chain/target/match by that name.
: uid=4512
Unable to complete the requested operation due to: An invalid exit code (1) was returned from the server broker.osc.locati.cc.  This indicates an unexpected problem during the execution of your request.
Reference ID: 4352dbfc93240e4bebe3ab8a08d73a9b

I think there is some kind of problem with the firewall, config, but I'm not sure...

**Comment by tiwillia** [comment]
I can verify, with a fresh Origin m4 installation using oo-install on top of Centos-6.5-minimal, that scalable applications can successfully be created. 

@danmcp we can close this out.

@fale if you are still experiencing this problem, please re-open this issue and upload the contents of `/tmp/openshift- deploy.log` from your installation so that we have the necessary data to troubleshoot it.
