### ISSUE TITLE
oo-install fails to setup properly jenkins

### ISSUE THREAD

**Issue by Fale** [openshift/origin-server#5691]
I've installed oo-install on a clean CentOS 6.5. If I try to enable jenkins for some gear, it creates properly the jenkins gear, but is not able to add the job.

Unable to complete the requested operation. Show less
Shell command '/sbin/runuser -s /bin/sh 53e1d65ed8fdedff2100010a -c "exec /usr/bin/runcon 'unconfined_u:system_r:openshift_t:s0:c3,c727' /bin/sh -c \"/var/lib/openshift/53e1d65ed8fdedff2100010a/jenkins-client/bin/install --version 1\""' returned an error. rc=1
Could not disable job 'nodejs-build' in Jenkins server:
   
Continuing anyway.
Could not add job 'nodejs-build' in Jenkins server:
   create_job status: 000
You'll need to correct this error before attempting to embed the Jenkins client again.
application is not scalable

I have selinux enabled in permissive mode

**Comment by tiwillia** [comment]
I can verify, with a fresh Origin m4 installation using oo-install on top of Centos-6.5-minimal, that this issue is not present (after working around #6193 by installing `java-1.7.0-openjdk`).

@danmcp we can close this one.

@Fale if you are still experiencing this problem, please re-open this issue and provide the `/tmp/openshift-deploy.log` from your installation.
