### ISSUE TITLE
Build of OpenShift Origin gems / rpms

### ISSUE THREAD

**Issue by david-strejc** [openshift/origin-server#6157]
Hi,

is there any way to build rpms for updating M4 version of OpenShift Origin?

I thing there are many bugs fixed and we have infrastructure build on OpenShift Origin - so we need to update those bugs somehow. 

Thanks

**Comment by tiwillia** [comment]
@david-strejc Sorry for the late reply.

The instructions to build a "nightly" version of the rpms is detailed in the [rel-eng/build_instructions/](https://github.com/openshift/origin-server/tree/master/rel-eng/build_instructions) readme file. There are several repo files and a script in this directory to assist with the build.

Since it has been some time, we are going to go ahead and close this issue. If you have any further questions, please don't hesitate to open it back up.

@danmcp can you close this one?
