### ISSUE TITLE
haproxy logs work flow 

### ISSUE THREAD

**Issue by ashishranjan2404** [openshift/origin-server#6290]
where does openshift configure haproxy to listen to network event for a particular severity and write it in their /var/lib/openshift/uuid/app-root/logs/haproxy.logs . 

where is syslogd or rsyslog deamons configured to log the haproxy logs ?

**Comment by tiwillia** [comment]
The haproxy cartridge uses the default logging mechanisms for Haproxy 1.4. Instead of sending output to a log file, we allow output to be directed to `STDOUT`. When starting haproxy, a pipe is created to the openshift logshifter, which receives the `STDOUT` from haproxy. The pipe redirects the output to the `haproxy.log` file in the directory defined by the `OPENSHIFT_HAPROXY_LOG_DIR` environment variable. You can see this in the below code:

https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-haproxy/bin/control#L72-L81

If your goal is to change what is logged from haproxy, you can modify the haproxy configuration file yourself and add configuration to manipulate the logs. The configuration file is located in a gear with an haproxy cartridge at `~/haproxy/conf/haproxy.cfg`. See the `8. Logging` section of the [haproxy-1.4 configuration documentation](http://www.haproxy.org/download/1.4/doc/configuration.txt) for more information on what logging directives are available.

**Comment by tiwillia** [comment]
Since this isn't an actual issue, but a question, we can close this @danmcp.

@ashishranjan2404 please feel free to reach out on [stackoverflow](http://stackoverflow.com/questions/tagged/openshift) or on freenode irc at #openshift for additional assistance.
