### ISSUE TITLE
Consider upgrading Modernizr JS library

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin-server#6313]
Hi,

On OpenShift Online, the following warning can be seen in the console (seems to appear for most pages in the webapp):

> 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

This comes from a modernizr.min.js file which has the following comment at the top:

> // Modernizr v1.7  www.modernizr.com

As the latest version of the [Modernizr JS library](https://modernizr.com/news) is 3.2.0, it seems likely that this warning has been fixed in subsequent versions. Would you consider updating the version of Modernizr in use?

I'm using Chrome 46.

Jonathan

**Comment by tiwillia** [comment]
@jawnsy Thanks for submitting this. I was confused by it at first, but realize that you mean that the error shows up in the Chrome developer console, not on the actual website. I can see the error in the developer console.

Note that I do not see the error in the latest firefox.

**Comment by jawnsy** [comment]
Sorry, yes -- the word "console" is pretty heavily overloaded :)

It makes sense that Firefox doesn't have the same error, since Firefox isn't based on the WebKit engine as Chrome is (well, was, as it's now using Blink but I think still uses WebKit vendor prefixes)

**Comment by jawnsy** [comment]
Welp, I just installed OpenShift v3 locally and I don't see this problem, so I guess this was resolved at some point (looks like the whole UI was rewritten in Angular). Should we just close this issue?

**Comment by tiwillia** [comment]
@jawnsy no, we aren't going to close this just yet. OpenShift v3 is the latest and greatest (and a complete re-write in another language), but what you use on Openshift.com is still what is here in the openshift/origin-server repository.

We definitely would prefer to fix this. Its on our to-do list, although it is not high priority since the issue only produces a warning.

**Comment by dinhxuanvu** [comment]
@jawnsy Thanks for bringing up the issue to us. I currently have a bugzilla that's created for this specific issue and I'm working to verify the modernizr 2.6.2 to see if it is ready to be merged to upstream. From what I've tested, the 2.6.2 version has fixed the problem. I'll keep you updated on the issue when I have more info. :)

**Comment by dinhxuanvu** [comment]
@jawnsy A PR will be merged soon to upgrade the modernizr js library to 2.6.2 and it should eliminate the warning that you mentioned. Thanks again for reporting the issue. If you want to verify the issue after the merge, please feel free to do so. Otherwise, please close the issue when you have a chance. Cheers!

**Comment by jawnsy** [comment]
I trust you ;)

Thanks for the quick work!

**Comment by dinhxuanvu** [comment]
Haha, I'll try to live up to that trust. Please continue to submit issues if you find ones. We certainly appreciate your contribution.

**Comment by jawnsy** [comment]
Don't mind me, just wanted to add a reference to the pull request for posterity...

https://github.com/openshift/origin-server/pull/6318
