### ISSUE TITLE
openshift origin cartridge phpmyadmin

### ISSUE THREAD

**Issue by luispimenta** [openshift/origin-server#6367]
I'm installing OpenShift origin m4, I create a normal web application, but when I add the phpmyadmin cartridge, it creates the _phpmyadmin.conf file inside the folder /etc/httpd/conf.d/openshift/ID_APP/ with an invalid line .

`ProxyPass / phpmyadmin http://127.10.75.3:8080/phpmyadmin/ retry = 0`
`ProxyPassReverse / phpmyadmin http://127.10.75.3:8080/phpmyadmin/`
`ProxyPassReverse / phpmyadmin http://teste-red4sis.apps.red4sis.in/`

which was to be only:

`ProxyPass / phpmyadmin http://127.10.75.3:8080/phpmyadmin/ retry = 0`
`ProxyPassReverse / phpmyadmin http://127.10.75.3:8080/phpmyadmin/`

Thus I can not access the application, because when I enter the url, is redirecting to phpmyadmin.

Does anyone know how to fix this?

thank you

**Comment by dinhxuanvu** [comment]
Hi Luis,

I'm not sure if someone wrong may occur during the phpmyadmin installation or not but the configuration file you included above is not correct.

The third line: ```ProxyPassReverse / phpmyadmin http://teste-red4sis.apps.red4sis.in/``` is missing the ```phpmyadmin``` at the end for some reason. You can just modify the file to change that line to ```ProxyPassReverse / phpmyadmin http://teste-red4sis.apps.red4sis.in/phpmyadmin``` and it should resolve your issue.

Give it a try and let me know if it works for you :).

Vu

**Comment by luispimenta** [comment]
Correct, it works! But I have to automate it, because I can not stand having to manually changing whenever I create an application! You know help me?

**Comment by dinhxuanvu** [comment]
@luispimenta Let me look into it a bit. Will get back to you on that :).

**Comment by luispimenta** [comment]
Ok, I'll be awaiting! I am developing a system that will automatically create applications and add wordpress phpmyadmin, so it is costly to manually edit each application this file! Must be a bug that adds this line. Thank you for now !

**Comment by dinhxuanvu** [comment]
Hi Luis,

So sorry for the delay. Unfortunately, the issue with phpMyAdmin is due to the fact that the packages (rpm) in the mirror (M4 version), that oo-install is using, are pretty old and outdated. Unfortunately, we are currently not planning to release a new version (M5) for OpenShift V2. You can still fix the issue manually like I suggested in previous comment or I HIGHLY recommend you to try out the new OpenShift V3 which eventually will replace OpenShift V3. The new OpenShift V3 is built on Docker and Kubernetes so there are a lot of exciting and great things to work with. Check this link for more info: https://github.com/openshift/origin/blob/master/README.md#getting-started

Thanks,
Vu

**Comment by luispimenta** [comment]
Got it. Thank you for your time and for your cooperation! :)
